services:
    postgres:
        image: postgres:16-alpine
        container_name: ehop_db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ${POSTGRES_VOLUME_PATH:-./data/postgres}:/var/lib/postgresql/data
            - ../backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        networks:
            - app_network
        restart: unless-stopped

    backend:
        build:
            context: ..
            dockerfile: deploy/Dockerfile.backend
        container_name: ehop_server
        env_file: .env
        environment:
            DB_HOST: postgres
        depends_on:
            - postgres
        volumes:
            - ${BACKEND_LOGS_PATH:-./logs/backend}:/app/logs
        networks:
            - app_network
        restart: unless-stopped

    frontend:
        build:
            context: ..
            dockerfile: deploy/Dockerfile.frontend
            args:
                VITE_API_URL: ${VITE_API_URL:-}
        container_name: ehop_nginx
        env_file: .env
        environment:
            SSL_DOMAIN: ${SSL_DOMAIN}
        volumes:
            - ${SSL_CERTS_PATH:-./certs/ssl}:/etc/nginx/ssl
        depends_on:
            - backend
        networks:
            - app_network
        restart: unless-stopped

networks:
    app_network:
        name: ehop_network
